{% set name = "napari-segment" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_segment-{{ version }}.tar.gz
  sha256: 8d99e78201fba9102897f0fc56a48d97975586b01189c6c258c863b5b4af6257

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - dask-core
    - imageio-ffmpeg
    - matplotlib-base
    - napari
    - nd2
    - numpy
    - python >=3.8,<3.11
    - scikit-image
    - zarr

test:
  imports:
    - napari_segment
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aaristov/napari-segment
  summary: Segment organoids and measure intensities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
